yykamei/thwack

.github/workflows/ci.yml
I want to run tests for macOS, too.
=> Enable macOS testing

.github/workflows/changelog.yml, .github/workflows/release.yml
Close #21 
I want to release the new version on GitHub Actions.
This new workflow is responsible for creating a GitHub release as well
as publishing it on crates.io.
=> Add a new workflow: Release

src/matched_path.rs
Previously, `positions` were calculated by searching the relative path
from the left. So,  if the `relative` is `"src/app/bold/choose/abc.txt"`
and `query` is `"abc"`, the `positions` would be `[4, 8, 13]`, instead
of `[20, 21, 22]`, even though the latter matches better.
In many cases, users would expect the `query` should match the basename
of a file path rather than intermediate directories. So, I hope this
makes sense for many people.
=> Fix the calculation of `positions`

src/matched_path.rs
Reverts yykamei/thwack#47
I found out `positions()` doesn't have to be exposed to the caller of `MatchedPath`.
=> Revert "Change the type of `positions` and add `positions()`"

src/cli.rs, src/matched_path.rs
=> Emphasize matched characters by styling with bold

.github/workflows/release.yml, src/args.rs, src/cli.rs
Close #44 
In addition, I refactored the `args` module a bit and added `tests`
module. I'm going to set commit hash and compiled date for this output.
=> Add --version option

.github/workflows/changelog.yml, .github/workflows/release.yml
https://github.com/github-changelog-generator/github-changelog-generator/releases/tag/v1.16.3
https://github.com/github-changelog-generator/github-changelog-generator/releases/tag/v1.16.4
Changes:
https://github.com/github-changelog-generator/github-changelog-generator/compare/v1.16.2...v1.16.4
=> Bump github-changelog-generator from v1.16.2 to v1.16.4

.github/workflows/changelog.yml
A shell variable should start with `$` 👻
=> Fix changelog.yml to correctly refer to a shell variable

.github/workflows/release.yml, src/cli.rs
It would be useful for users to download the thwack binary.
=> Upload artifacts when releasing

src/cli.rs
Ctrl-p and Ctrl-n are usually expressed as Up/Down in Emacs and used for
searching command history in Bash.
I guess some terminal users may want to move the cursor with these keys,
so I added the new key events for the selection movement.
=> Allow to move selections with Ctrl-p and Ctrl-n

src/cli.rs
Close #20
It would be helpful to show the status and help lines.
In addition, it'd be a bit cool 🆒
=> Add the status and help lines at the bottom

src/args.rs, src/cli.rs, src/lib.rs, tests/helper.rs, tests/show_help.rs
Part of #121 
This project lacks integration tests. This PR first introduces `show_help.rs` to test the functionality to show the help message.
=> [refactor] Add show_help.rs for integration tests

.github/workflows/release.yml
Fix the error on this workflow.
https://github.com/yykamei/thwack/runs/3284904307?check_suite_focus=true
=> Fix the lint error by ShellCheck through actionlint

tests/change_selection.rs, tests/filter_by_query.rs, tests/helper.rs
Make `buf!` receive multiple expressions to facilitate passing expected
bytes.
This is a part of #121.
=> Make `buf!` receive multiple expressions

Cargo.lock, Cargo.toml, src/args.rs, src/cli.rs, src/lib.rs, src/logger.rs
`--log-file` option might be useful to debug this program. By default, the logging feature is disabled.
=> Support --log-file option to write logs

src/args.rs, src/cli.rs, src/lib.rs, src/preferences.rs, src/status_line.rs
I'm planning to make thwack extract configurations from environment
variables. This feature might be good to implement for `Preferences`
(previously, `ParsedArgs`), but it is difficult for me to go on within
`args.rs`.
=> Separate Preferences and StatusLine

src/cli.rs
`cli.rs` becomes a bit of difficult to maintain, so I introduced
`Runner` and `Writer` structs to the module and let them handle terminal
events and output.
=> Refactor cli.rs to handle mutable variables within a struct

.github/workflows/changelog.yml
Update `changelog.yml` to use composite actions.
=> Use yykamei/actions-update-changelog to update changelog

.github/workflows/ci.yml
So far, I don't need textlint for this project.
=> Disable VALIDATE_NATURAL_LANGUAGE

src/cli.rs, src/matched_path.rs
I found I don't have to separete Writer from Runner. Actually, it was hard to pass data to Writer from Runner for me. Runner has much information, but they deserve to have them in its own properties.
=> Integrate Writer into Runner

.github/workflows/ci.yml, .github/workflows/release.yml
😢 https://github.com/actions-rs/toolchain/issues/216
=> Migrate from actions-rs/toolchain to dtolnay/rust-toolchain

src/lib.rs, src/query.rs
I'm refactoring this project.
`Query` will be responsible for storing input query as well as the cursor position. With this struct, users can move the cursor to left/right to modify the query characters in an arbitrary positions.
=> Add Query to store input query as well as cursor position

src/candidates.rs, src/lib.rs, src/query.rs
`Candidates` is a new implementation, which will replace `Finder`. I want to make filtering feature simpler with this struct.
=> Add Candidates

src/candidates.rs
`Candidates` will have responsibility to handle user selection. When a user select a target from the candidates, the program must consider the following things:
* How many paths can the program show in the current window? They should be within the window height.
* The program should handle cursor selection at the beginning/end of paths. Cursor selection should move within the visible paths.
This change aims to achieve the goal.
=> Support selection in Candidates

src/candidates.rs, src/cli.rs, src/invoke.rs, src/lib.rs
`invoke()` was difficult to test, but I think it's possible to test it if it's extracted as a standalone function.
=> Extract invoke() for testability
