- .github/dependabot.yml
https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore
> Dependabot version updates now have the ability to ignore major, minor, or patch updates for a specific dependency or set of dependencies.
🎉
> Update dependabot.yml to ignore patch and minor updates on actions

- .github/workflows/changelog.yml
- .github/workflows/release.yml
This is a part of #21.
A changelog should be always updated when the default branch gets updated. This new workflow will get triggered on the `push` event on the default branch of this repository. To test the functionality, I added the `workflow_dispatch` event as well.
> Add Changelog action to automatically update

- src/cli.rs
- src/finder.rs
- src/lib.rs
- src/matched_path.rs
Close #30 
We can sort slices with this struct with the implementation of `Ord` for
`MatchedPath`. This will be useful to show plausible file path
candidates.
> Implement Ord for MatchedPath

- src/matched_path.rs
`MatchedPath::positions()` will be used to emphasize what characters
matches in a relative path. In order to expose this function, I changed
the type of the field `positions` from `VecDeque` to `Vec`. I wanted
to use `as_slice` instead of `as_slices`, and I'd like to avoid calling
[`make_contiguous`](https://doc.rust-lang.org/alloc/collections/vec_deque/struct.VecDeque.html#method.make_contiguous).
`VecDeque` was still used to calculates positions, but the result will
be stored as `Vec` from this patch.
> Change the type of `positions` and add `positions()`

- Cargo.lock
- Cargo.toml
- src/args.rs
- src/cli.rs
- src/error.rs
- src/main.rs
Using `libc::execvp`, thwack doesn't have to care about the output by
`Command`. Plus, it can replace itself with the new process image on
UNIX-like systems. On Windows, the behavior itself might be the same as
before.
> Replace `Command` with `libc::execvp`

- src/args.rs
From this patch, thwack handles an option like value as **option**.
For example, these arguments are invalid:
```console
thwack --exec --help                # Error
thwack --exec --version             # Error
thwack --starting-point --exec=open # Error
```
However, an option suffixed with `=` still accepts the value as is.
```console
thwack --exec=--help                          # OK
thwack --starting-point=--special-directory-- # OK
```
In addition, this patch introduces `--` (double hyphens) to assume the
rest arguments as `query`. If more than one rest arguments are remained,
these arguments are just joined by a whitespace.
> Handle option like value as option

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/finder.rs
- src/matched_path.rs
According to the rust API, `str::chars` does not seem to support
grapheme clusters.
https://doc.rust-lang.org/std/primitive.str.html#method.chars
This patch introduces `unicode-segmentation` to support such characters.
> Use grapheme cluster to detect correct indices

- .gitignore
- src/cli.rs
- src/finder.rs
- src/lib.rs
- src/starting_point.rs
This struct is intended for a caller of `Finder` to specify the correct
`starting_point` in advance. **The correct `starting_point`** means the
path which is valid in terms of character encdoing, and really exists in
a file system; in other words, it can be `canonicalize`d safely.
With this refactoring, each `ConsumedDir` does not have to call
`canonicalize` because `Finder` can get absolute path due to the
`canonicalize`d `starting_point`.
> Add a new struct: StartingPoint

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/matched_path.rs
Close #57 
Sometimes, a user may come across the case that some of the file
candidates are too long for the terminal to wrap them and cause the
broken screen. This patch tries to alleviate such a situation to omit
them with an ellipsis. Some of the matched characters will be lost
because of the omission, but I want to prioritize to maintain the screen
not broken.
> Returns Chunks based on the terminal size

- src/cli.rs
Fix #31 
Previously, pattern matching inadvertently catched the
`KeyModifiers::NONE`. This caused the weird behavior that a user cannot
type uppercase characters. This patch relaxes the restriction.
> Relax the key event capturing without modifiers

- .github/workflows/changelog.yml
- .github/workflows/release.yml
Reverts yykamei/thwack#75 because of this error https://github.com/yykamei/thwack/actions/runs/921599583
1.16.4 hasn't been published so far.
> Revert "Bump github-changelog-generator from v1.16.2 to v1.16.4"

- .github/workflows/release.yml
Use the environment variable `CARGO_REGISTRY_TOKEN`  to publish a new package.
See https://doc.rust-lang.org/cargo/reference/config.html#registrytoken for more details about this parameter.
> Set CARGO_REGISTRY_TOKEN for the release workflow

- .github/workflows/changelog.yml
As #77 couldn't be merged, the Docker image of this gem is still not available.
I guess we should use it as a Ruby gem to follow the latest version.
> Use github-changelog-generator installing as a gem

- Cargo.lock
- Cargo.toml
- src/error.rs
Close #97 
Summary:
Bump crossterm from 0.19.0 to 0.20.0. This requires extra work to remove
`impl From<crossterm::ErrorKind> for Error` because `crossterm::ErrorKind`
became just an alias of `io::Error`. We don't have to convert crossterm
specific errors. See https://github.com/crossterm-rs/crossterm/pull/553
for more details.
Release note:
https://github.com/crossterm-rs/crossterm/releases
Changelog:
https://github.com/crossterm-rs/crossterm/blob/master/CHANGELOG.md
> Bump crossterm from 0.19.0 to 0.20.0

- scripts/gh_pr_create.sh
gh-pr-create(1) should not be called if there are no changes.
> Do nothing if there are no changes

- src/cli.rs
- src/finder.rs
- src/matched_path.rs
`MatchedPath::relative` cannot be accessed because `starting_point`
sometimes differs because of the `--starting-point` option. With
`--starting-point`, we should not use the *relative* path.
In the first place, I believe there are few commands to require relative
paths for their argument. Thus, I made `invoke` receive an absolute
path.
> Pass absolute path to the specified command

- scripts/gh_pr_create.sh
I should have made the script check the difference from `origin/main`.
> Fix the diff algorithm of gh_pr_create.sh

- src/cli.rs
The `selection` variable starts with `0`, so we have to check whether
the `selection` reaches the bottom of the window by subtracting one from
the number of paths.
> Fix the selection disappearance at KeyCode::Down

- src/cli.rs
When the Resize event occurs, `paths` must be updated to fix them to the
window size.
> Fix Resize event handling to update paths

- .github/workflows/ci.yml
- src/cli.rs
- src/matched_path.rs
`MatchedPath` can return chunks of `absolute`, so I refactored the
implementation.
In addition, I added `truncated_absolute` to allow us to get an absolute
path truncated within the window.
> Refactor MatchedPath to return chunks of absolute

- src/cli.rs
If the `selection` remains when the resize event happens, selected
cursor sometimes disappears. This patch tries to keep the selection
within the window.
> Change selection when the resize event happens

- tests/helper.rs
- tests/show_version.rs
This is a part of #131.
I want to test the functionality of `--version` to confirm the version is output with this option.
> [refactor] Add show_version.rs to test --version

- src/cli.rs
- src/lib.rs
- src/main.rs
- src/matched_path.rs
- src/terminal.rs
- tests/helper.rs
- tests/show_help.rs
- tests/show_version.rs
In order to stub the functions of `terminal`, I decided to wrap the
`terminal` module from `crossterm`. This new trait, `Terminal`, is
responsible for calling terminal-specific functions.
> [refafctor] Add Terminal trait for testing

- src/args.rs
- src/cli.rs
- src/matched_path.rs
Users might want to see the relative path on the status instead of the
absolute path. This option allows them to show the relative path.
In addition, I added another option value "none" to hide the status-line
itself.
Honestly, this option is intended for testing use, but I hope this would
be convenient.
> Add --status-line=<absolute|relative|none>

- tests/filter_by_query.rs
- tests/helper.rs
This is a part of #121
This new function is responsible for replacing `'\\'` with `'/'` to test
the `cli` module with the same test cases on both Windows and Unix.
> Add Buffer::normalize_path to ignore the difference between Windows and Unix

- src/cli.rs
- tests/change_selection.rs
- tests/helper.rs
Moving down behavior is broken. This patch fixes the poor behavior and
prevents the selection from exceeding the bottom of paths.
It might be a part of #121.
> Fix move down behavior

- .github/workflows/release.yml
Fix #183
Now, `macOS-latest` uses macOS 11 Big Sur, so we don't have to set `SDKROOT`.
https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/
> Use the default macOS SDK in release.yml

- src/error.rs
`insufficient_query` and `ErrorKInd::InsufficientQuery` are not used.
> Remove unused ErrorKind

- src/cli.rs
Fix #198 
A directory sometimes includes directories that cannot be read.
Previously, if the starting point contains such directories, this
program exits as status 1. This might be inconvenient.
So, this patch makes thwack skip such directories.
> Ignore error paths

- src/args.rs
This option will be used later.
We're planning to support `.gitignore` to exclude ignorable paths from
the result of thwack.
> Add --no-gitignore

- Cargo.lock
- Cargo.toml
- src/args.rs
- src/cli.rs
- src/finder.rs
In most cases, it's rare to search files that are listed in `.gitignore`
or files in `.git/`. This patch introduces `git2` and lets us ignore
files that are listed in `.gitignore`.
> Respect .gitignore

- src/cli.rs
- src/preferences.rs
Sometimes, it'd be convenient to always set the `--exec` option with a
favorite command. So, I want to make thwack read the environment
variables.
I suppose this should be configured in shell configurations like
`.bashrc` or `.zshrc`.
> Read the environment variables: THWACK_LOG_FILE and THWACK_EXEC

- Cargo.toml
- src/args.rs
- src/status_line.rs
Now, we can migrate the Rust edition for thwack from 2018 to 2021.
See https://doc.rust-lang.org/beta/edition-guide/rust-2021/index.html for more details.
> Migrate the edition from 2018 to 2021

- src/args.rs
- src/cli.rs
- src/preferences.rs
I prefer the behavior that command-line arguments take precedence over environment variables, which means `THWACK_EXEC=ls thwack --exec=exa` will execute `exa` instead of `ls` when a user hits the Enter key on a selected path.
Note AWS CLI also does the same way:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence
> Make command-line arguments take precedence over envs

- src/cli.rs
We've already updated to skip errored paths,
so we don't have to care about this comment anymore.
> Remove resolved TODO comment

- src/finder.rs
`std::path::Path::is_dir` and `std::path::Path::is_file` will traverse symbolic links. First, I thought I should skip symbolic links from Finder results, but I reconsidered making thwack traverse files/directories. These APIs will return `false` when symbolic links are broken or not accessbile by a user, so permission problems might not rarely happen. Still, I'm concerned about security issues about traversing, but I decided to keep access to them.
> Remove TODO about symbolic link

- Cargo.toml
Update the value of [rust-version field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) from `1.59.0` to `1.71.0`. I want to make sure the binary will be built with the current latest stable version of Rust.
> Bump rust-version from 1.59.0 to 1.71.0

- Cargo.lock
- Cargo.toml
- src/args.rs
- src/finder.rs
- src/logger.rs
- src/matched_path.rs
- src/preferences.rs
- tests/change_selection.rs
- tests/copy_selection.rs
- tests/filter_by_query.rs
- tests/handle_resize.rs
- tests/show_help.rs
- tests/show_version.rs
This crate tests itself by seeing the difference between actual output to standard output and expected bytes.
Previously, the built-in `assert_eq` does not show the difference between the left/right values by showing what characters are different from the other side. So, it was difficult for developers to figure out why tests fail.
From this motivation, I want to introduce `pretty_assertions`, which provides `assert_eq` with more colorful diffs.
See the following repository for more details about `pretty_assertions`.
https://github.com/rust-pretty-assertions/rust-pretty-assertions
> Introduce pretty_assertions

- .github/workflows/ci.yml
- .github/workflows/release.yml
Recently, I got an error like this:
https://github.com/yykamei/thwack/actions/runs/6452098798/job/17546604788?pr=776
```
Err:2 mirror+file:/etc/apt/apt-mirrors.txt jammy-updates/main amd64 libx11-xcb-dev amd64 2:1.7.5-1ubuntu0.2
404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/libx/libx11/libx11-xcb-dev_1.7.5-1ubuntu0.2_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
Fetched 26.0 kB in 1s (42.6 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
I'm not sure how to fix this problem, but I want to try running `apt update` before `apt install`.
> Run `apt update` before `apt install`

- .github/workflows/ci.yml
According to https://github.com/super-linter/super-linter/issues/4150, Super-Linter's ownership was transferred to @super-linter.
> Use super-linter/super-linter instead of github/super-linter

- .github/workflows/release.yml
[actions-rs/cargo](https://github.com/actions-rs/cargo) has been archived 😢 
I decided to migrate to [taiki-e/install-action](https://github.com/taiki-e/install-action) to support cross platform build.
> Migrate from actions-rs/cargo to taiki-e/install-action@cross

- src/query.rs
Implementing [`Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) will automatically implement `ToString`, so I switched from defining `to_string` by hand to implementing `Display`.
> Implement Display instead of defining to_string by hand

- src/cli.rs
- src/query.rs
I'm planning to support left/right move.
Query will support the keyboard events.
In this patch, I first want to replace the primitive `String` with `Query` in advance.
> Use Query in cli.rs

- src/query.rs
When Query's value is changed, a terminal usually has to move cursor. At this time, the terminal should know how many cells should it move. If the last value was emoji, the terminal should move the cursor by 2 most of time.
This patch makes `Query` return the number of cells should be moved.
> Return usize of cjk width when query position is changed

- src/candidates.rs
I think `visible_paths_length()` doesn't have to move owned self for consistencey. Other functions for the `impl Candidates` have already been implemented as `&mut self`, such as `move_up()`.
> Change the interface of visible_paths_length()

- src/candidates.rs
The selected target will be used from the callers of `Candidates`.
This patch adds a new functionality to provide the selected target.
> Add selected() in Candidates

- src/status_line.rs
`StatusLine` is so simple that I think this type should be copied/cloned for convenience.
> Make StatusLine derive Copy and Clone

- src/candidates.rs
- src/cli.rs
- src/lib.rs
- src/query.rs
- src/screen.rs
`cli::Runner` is a bit difficult to update for adding new features, so I want to replace it with the new implementation, `Screen`.
`Screen` will behave like `cli::Runner`, but it's written for extensibility. Still, this struct is huge, but I believe it's better than `cli::Runner`.
This patch just adds `Screen`. I will replace `cli::Runner` with it later.
> Add Screen to replace cli::Runner

- src/screen.rs
Close #73 
With this patch, a user can move the cursor left/right. This behavior might be useful when the user wants to tweak the search query.
> Support key events: Left and Right

- src/logger.rs
Sometimes, tests on this file fail. I'm not sure why, but I think the fix to change the assertinos may resolve this problem.
> Make tests on src/logger.rs robust

- src/screen.rs
thwack has already supported the default Bash key binding (emacs) such as CTRL-P as Up and CTRL-N as Down. Now, I want to support CTRL-H as Backspace. I'm used to this key binding on shell terminal, so I want to use it on thwack, too.
> Support CTRL-H, same as Backspace

- src/lib.rs
- src/tree.rs
The current implementation has a performance problem because it always get all files when the passed `query` changes. This significantly increases I/O. I want to avoid the call of I/O by storing all files in memory. This development decision might affect the memory usage, but I want to first try it.
This patch just adds `Tree` for the purpose of storing all possible files, which is not yet used by other modules.
> Add Tree to store all tree files in memory

- src/candidates.rs
- src/screen.rs
- src/tree.rs
In the previous pull request below, `Tree` has been introduced in this repository to store the all files under the `starting_point`.
https://github.com/yykamei/thwack/pull/1059
This patch uses `Tree` in `Screen` and `Candidates` to reduce I/O of getting files.
> Use Tree in Screen and Candidates

- src/candidates.rs
- src/matched_path.rs
- src/query.rs
- src/tree.rs
Previously, the result of `sort` for `MatchedPath` was odd. For example, if I put "user.rb" in `query`, I got `lib/admin_user.rb` first, instead of `lib/user.rb`. I expected `lib/user.rb` should be prioritized over `lib/admin_user.rb` because `lib/user.rb` exactly matched in the basename of the path.
That's why I updated `Ord` impl for `MatchedPath`.
> Update the Ord impl for `MatchedPath`

- src/screen.rs
Although the current thwack implementation loads file tree in memory at the beginning of this program, sometimes a user might want to reload the file tree for some reason. I think it's worth adding a new feature to reload the file tree when the user commands to reload it.
This patch allows a user to reload the file tree when the user type Ctrl-R.
> Support Ctrl-R to reload the file tree
